# -*- coding: utf-8 -*-
"""vis.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/177QWdxzl-PcL1cFfHo9ROqTLlY4jjMBt
"""

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import subprocess
import sys

# Check if the user provided the dataset file path as an argument
if len(sys.argv) != 2:
    print("Usage: python vis.py <file_path>")
    sys.exit(1)

# Get the file path from the command-line argument
file_path = sys.argv[1]

try:
    # Load the dataset
    df = pd.read_csv(file_path)
    
    # Calculate the correlation matrix
    numeric_columns = ['Age','Survived','Pclass','SibSp', 'Parch', 'Fare']
    correlation_matrix = df[numeric_columns].corr()
    
    # Create a heatmap
    plt.figure(figsize=(10, 8))
    sns.heatmap(correlation_matrix, annot=True, cmap='coolwarm', linewidths=0.5)
    plt.title('Correlation Heatmap')
    
    # Save the visualization as 'vis.png'
    plt.savefig('vis.png')
    
    # Display the visualization
    plt.show()
    
except FileNotFoundError:
    print(f"File not found: {file_path}")

except Exception as e:
    print(f"An error occurred: {e}")
    
# Call the 'model.py' script using subprocess
subprocess.run(["python3", "model.py","res_dpre.csv"])
